const coursesConstants = {
  FETCH_COURSES_REQUEST: 'FETCH_COURSES_REQUEST',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
};

export default coursesConstants;
